---
- name: look for install in {{ splunk_uf_install_dir }}...
  become: yes
  stat:
    path: '{{ splunk_uf_install_dir }}'
  changed_when: False
  register: splunk_uf_binary
- when: not splunk_uf_binary.stat.exists
  block:
    - name: downloading {{ splunk_uf_url }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ splunk_uf_url }}'
        dest: '{{ splunk_uf_tmp_tgz }}'
        mode: 0644
        checksum: '{{ splunk_uf_checksum }}'
        timeout: '{{ splunk_uf_dl_timeout_secs }}'
    - name: mkdir {{ splunk_uf_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ splunk_uf_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ splunk_uf_tmp_tgz }} to {{ splunk_uf_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ splunk_uf_tmp_tgz }}'
        dest: '{{ splunk_uf_install_dir }}'
        creates: '{{ splunk_uf_install_subdir }}'
  always:
    - name: rm {{ splunk_uf_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ splunk_uf_tmp_tgz }}'
        state: absent
- name: linking {{ splunk_uf_link_dir }} to {{ splunk_uf_install_subdir }}
  become: yes
  become_user: root
  file:
    src: '{{ splunk_uf_install_subdir }}'
    dest: '{{ splunk_uf_link_dir }}'
    state: link
- name: add splunk uf binaries to default shell
  become: yes
  become_user: root
  with_items:
    - f: splunk_uf.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
